// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateUser(ctx context.Context, name string) (User, error)
	DeleteUserById(ctx context.Context, id uuid.UUID) error
	DeleteUserByName(ctx context.Context, name string) error
	GetUserById(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByName(ctx context.Context, name string) (User, error)
	UpdateUserById(ctx context.Context, arg UpdateUserByIdParams) (User, error)
	UpdateUserByName(ctx context.Context, arg UpdateUserByNameParams) (User, error)
}

var _ Querier = (*Queries)(nil)
